on:
  push:
    branches: main
    paths:
      - front/**
      - .github/workflows/build-front.yml
      - .github/workflows/reusable-build.yml
      - docker-bake.hcl
  workflow_dispatch:

jobs:
  build-and-push:
    secrets: inherit
    permissions:
      packages: write
    uses: ./.github/workflows/reusable-build.yml
    with:
      target: frontend
