on:
  push:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: --check --verbose
          src: dalai
